import '../models/product_model.dart';

class DummyData {
  static List<ProductModel> getProducts() {
    return [
      ProductModel(
        id: '1',
        title: 'Ø¢ÙÙÙÙ 15 Ø¨Ø±Ù ÙØ§ÙØ³ 256GB',
        description: 'ÙØ§ØªÙ Ø£ÙÙÙÙ Ø¬Ø¯ÙØ¯ Ø¨Ø§ÙÙØ§ÙÙ ÙØ¹ Ø¶ÙØ§Ù Ø³ÙØ©Ø Ø´Ø§Ø´Ø© 6.7 Ø¨ÙØµØ©Ø ÙØ§ÙÙØ±Ø§ 48 ÙÙØ¬Ø§Ø¨ÙØ³Ù',
        price: 450000,
        oldPrice: 500000,
        currency: 'YER',
        images: ['https://picsum.photos/id/1/300/300', 'https://picsum.photos/id/2/300/300'],
        category: 'Ø¥ÙÙØªØ±ÙÙÙØ§Øª',
        subCategory: 'ÙÙØ§ØªÙ',
        sellerId: 'seller1',
        sellerName: 'ÙØªØ¬Ø± Ø§ÙØªÙÙÙØ©',
        sellerRating: 4.8,
        inStock: true,
        rating: 4.8,
        reviewCount: 120,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '2',
        title: 'Ø³Ø§ÙØ³ÙÙØ¬ S24 Ø§ÙØªØ±Ø§',
        description: 'ÙØ§ØªÙ Ø³Ø§ÙØ³ÙÙØ¬ Ø¬Ø§ÙØ§ÙØ³Ù S24 Ø§ÙØªØ±Ø§Ø Ø´Ø§Ø´Ø© 6.8 Ø¨ÙØµØ©Ø ÙØ§ÙÙØ±Ø§ 200 ÙÙØ¬Ø§Ø¨ÙØ³Ù',
        price: 380000,
        oldPrice: 420000,
        currency: 'YER',
        images: ['https://picsum.photos/id/3/300/300'],
        category: 'Ø¥ÙÙØªØ±ÙÙÙØ§Øª',
        subCategory: 'ÙÙØ§ØªÙ',
        sellerId: 'seller1',
        sellerName: 'ÙØªØ¬Ø± Ø§ÙØªÙÙÙØ©',
        sellerRating: 4.7,
        inStock: true,
        rating: 4.7,
        reviewCount: 95,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '3',
        title: 'ÙØ§Ø¨ØªÙØ¨ ÙØ§Ù Ø¨ÙÙ Ø¨Ø±Ù M3',
        description: 'ÙØ§Ø¨ØªÙØ¨ Ø§Ø­ØªØ±Ø§ÙÙ Ø¨Ø´Ø±ÙØ­Ø© M3Ø 16 Ø¬ÙØ¬Ø§ Ø±Ø§ÙØ 512 Ø¬ÙØ¬Ø§ SSD',
        price: 1800000,
        currency: 'YER',
        images: ['https://picsum.photos/id/5/300/300'],
        category: 'Ø¥ÙÙØªØ±ÙÙÙØ§Øª',
        subCategory: 'ÙØ§Ø¨ØªÙØ¨',
        sellerId: 'seller2',
        sellerName: 'Ø§ÙØ­Ø§Ø³ÙØ¨ Ø§ÙÙØªÙØ¯Ù',
        sellerRating: 4.9,
        inStock: true,
        rating: 4.9,
        reviewCount: 45,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '4',
        title: 'ØªÙÙÙØªØ§ ÙØ§ÙØ±Ù 2024',
        description: 'Ø³ÙØ§Ø±Ø© ØªÙÙÙØªØ§ ÙØ§ÙØ±Ù 2024Ø ÙÙÙÙ Ø£ÙØªÙÙØ§ØªÙÙØ ÙØ§ÙÙØ±Ø§ Ø®ÙÙÙØ©',
        price: 8500000,
        currency: 'YER',
        images: ['https://picsum.photos/id/9/300/300'],
        category: 'Ø³ÙØ§Ø±Ø§Øª',
        subCategory: 'Ø³ÙØ§Ø±Ø§Øª ÙÙØ¨ÙØ¹',
        sellerId: 'seller3',
        sellerName: 'ÙØ¹Ø±Ø¶ Ø§ÙØ³ÙØ§Ø±Ø§Øª',
        sellerRating: 4.6,
        inStock: true,
        rating: 4.6,
        reviewCount: 34,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '5',
        title: 'Ø´ÙØ© ÙÙ Ø­Ø¯Ø© - ØµÙØ¹Ø§Ø¡',
        description: 'Ø´ÙØ© 3 ØºØ±Ù ÙÙÙØ 2 Ø­ÙØ§ÙØ ØµØ§ÙØ© ÙØ¨ÙØ±Ø©Ø ÙÙÙØ¹ ÙÙÙØ²',
        price: 35000000,
        currency: 'YER',
        images: ['https://picsum.photos/id/12/300/300'],
        category: 'Ø¹ÙØ§Ø±Ø§Øª',
        subCategory: 'Ø´ÙÙ ÙÙØ¨ÙØ¹',
        sellerId: 'seller4',
        sellerName: 'Ø§ÙØ¹ÙØ§Ø±Ø§Øª Ø§ÙØ°ÙØ¨ÙØ©',
        sellerRating: 4.5,
        inStock: true,
        rating: 4.5,
        reviewCount: 12,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '6',
        title: 'ØºØ±ÙØ© ÙÙÙ ÙØ§ÙÙØ©',
        description: 'ØºØ±ÙØ© ÙÙÙ Ø®Ø´Ø¨ Ø²Ø§Ù - Ø³Ø±ÙØ± 160 Ø³ÙØ Ø¯ÙÙØ§Ø¨Ø ØªØ³Ø±ÙØ­Ø©',
        price: 650000,
        currency: 'YER',
        images: ['https://picsum.photos/id/15/300/300'],
        category: 'Ø£Ø«Ø§Ø«',
        subCategory: 'ØºØ±Ù ÙÙÙ',
        sellerId: 'seller5',
        sellerName: 'ÙØªØ¬Ø± Ø§ÙØ£Ø«Ø§Ø«',
        sellerRating: 4.3,
        inStock: true,
        rating: 4.3,
        reviewCount: 45,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '7',
        title: 'Ø«ÙØ¨ Ø±Ø¬Ø§ÙÙ ÙÙÙÙ',
        description: 'Ø«ÙØ¨ ÙÙÙÙ ØªÙÙÙØ¯Ù - ÙØ·Ù 100%Ø ÙÙØ§Ø³Ø§Øª ÙØ®ØªÙÙØ©',
        price: 15000,
        currency: 'YER',
        images: ['https://picsum.photos/id/17/300/300'],
        category: 'ÙÙØ§Ø¨Ø³',
        subCategory: 'Ø±Ø¬Ø§ÙÙ',
        sellerId: 'seller6',
        sellerName: 'ÙØªØ¬Ø± Ø§ÙÙÙØ§Ø¨Ø³',
        sellerRating: 4.6,
        inStock: true,
        rating: 4.6,
        reviewCount: 78,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '8',
        title: 'ÙØ¬Ø¨Ø© ÙÙØ¯Ù Ø¯Ø¬Ø§Ø¬',
        description: 'ÙÙØ¯Ù Ø¯Ø¬Ø§Ø¬ ÙØ¹ Ø£Ø±Ø² Ø¨Ø³ÙØªÙØ ØµÙØµØ©Ø Ø³ÙØ·Ø© (ØªÙÙÙ 4 Ø£Ø´Ø®Ø§Øµ)',
        price: 8000,
        currency: 'YER',
        images: ['https://picsum.photos/id/19/300/300'],
        category: 'ÙØ·Ø§Ø¹Ù',
        subCategory: 'ÙØ¬Ø¨Ø§Øª Ø±Ø¦ÙØ³ÙØ©',
        sellerId: 'seller7',
        sellerName: 'ÙØ·Ø¹Ù Ø§ÙØ£ØµÙÙ',
        sellerRating: 4.9,
        inStock: true,
        rating: 4.9,
        reviewCount: 234,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '9',
        title: 'ØµÙØ§ÙØ© ÙÙÙÙØ§Øª',
        description: 'Ø®Ø¯ÙØ© ØµÙØ§ÙØ© ÙØªØ¨Ø±ÙØ¯ ÙÙÙÙØ§Øª - ÙØ­Øµ ÙØªØ¹Ø¨Ø¦Ø© ØºØ§Ø² ÙØªÙØ¸ÙÙ',
        price: 5000,
        currency: 'YER',
        images: ['https://picsum.photos/id/21/300/300'],
        category: 'Ø®Ø¯ÙØ§Øª',
        subCategory: 'ØµÙØ§ÙØ©',
        sellerId: 'seller8',
        sellerName: 'Ø®Ø¯ÙØ§Øª Ø§ÙØµÙØ§ÙØ©',
        sellerRating: 4.5,
        inStock: true,
        rating: 4.5,
        reviewCount: 45,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '10',
        title: 'Ø¨ÙØ§Ù Ø³ØªÙØ´Ù 5',
        description: 'Ø¬ÙØ§Ø² Ø¨ÙØ§Ù Ø³ØªÙØ´Ù 5 - ÙØ³Ø®Ø© Ø¯ÙØ¬ÙØªØ§Ù + ÙØ¯ ØªØ­ÙÙ DualSense',
        price: 250000,
        currency: 'YER',
        images: ['https://picsum.photos/id/23/300/300'],
        category: 'Ø£ÙØ¹Ø§Ø¨',
        subCategory: 'Ø£Ø¬ÙØ²Ø© Ø£ÙØ¹Ø§Ø¨',
        sellerId: 'seller9',
        sellerName: 'ÙØªØ¬Ø± Ø§ÙØ£ÙØ¹Ø§Ø¨',
        sellerRating: 4.9,
        inStock: true,
        rating: 4.9,
        reviewCount: 156,
        createdAt: DateTime.now(),
      ),
    ];
  }
}