import 'product_model.dart';

class DummyData {
  static List<ProductModel> getProducts() {
    return [
      ProductModel(
        id: '1',
        title: 'Ø¢ÙÙÙÙ 15 Ø¨Ø±Ù ÙØ§ÙØ³',
        description: 'ÙØ§ØªÙ Ø£ÙÙÙÙ Ø¬Ø¯ÙØ¯ Ø¨Ø§ÙÙØ§ÙÙ ÙØ¹ Ø¶ÙØ§Ù Ø³ÙØ©',
        price: 450000,
        oldPrice: 500000,
        currency: 'YER',
        images: ['https://picsum.photos/id/1/300/300'],
        category: 'Ø¥ÙÙØªØ±ÙÙÙØ§Øª',
        subCategory: 'ÙÙØ§ØªÙ',
        sellerId: 'seller1',
        sellerName: 'ÙØªØ¬Ø± Ø§ÙØªÙÙÙØ©',
        sellerRating: 4.8,
        inStock: true,
        rating: 4.8,
        reviewCount: 120,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '2',
        title: 'Ø³Ø§ÙØ³ÙÙØ¬ S24 Ø§ÙØªØ±Ø§',
        description: 'ÙØ§ØªÙ Ø³Ø§ÙØ³ÙÙØ¬ Ø¬Ø§ÙØ§ÙØ³Ù S24 Ø§ÙØªØ±Ø§',
        price: 380000,
        oldPrice: 420000,
        currency: 'YER',
        images: ['https://picsum.photos/id/3/300/300'],
        category: 'Ø¥ÙÙØªØ±ÙÙÙØ§Øª',
        subCategory: 'ÙÙØ§ØªÙ',
        sellerId: 'seller1',
        sellerName: 'ÙØªØ¬Ø± Ø§ÙØªÙÙÙØ©',
        sellerRating: 4.7,
        inStock: true,
        rating: 4.7,
        reviewCount: 95,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '3',
        title: 'ÙØ§Ù Ø¨ÙÙ Ø¨Ø±Ù M3',
        description: 'ÙØ§Ø¨ØªÙØ¨ Ø§Ø­ØªØ±Ø§ÙÙ Ø¨Ø´Ø±ÙØ­Ø© M3',
        price: 1800000,
        currency: 'YER',
        images: ['https://picsum.photos/id/5/300/300'],
        category: 'Ø¥ÙÙØªØ±ÙÙÙØ§Øª',
        subCategory: 'ÙØ§Ø¨ØªÙØ¨',
        sellerId: 'seller2',
        sellerName: 'Ø§ÙØ­Ø§Ø³ÙØ¨ Ø§ÙÙØªÙØ¯Ù',
        sellerRating: 4.9,
        inStock: true,
        rating: 4.9,
        reviewCount: 45,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '4',
        title: 'ØªÙÙÙØªØ§ ÙØ§ÙØ±Ù 2024',
        description: 'Ø³ÙØ§Ø±Ø© ØªÙÙÙØªØ§ ÙØ§ÙØ±Ù 2024',
        price: 8500000,
        currency: 'YER',
        images: ['https://picsum.photos/id/9/300/300'],
        category: 'Ø³ÙØ§Ø±Ø§Øª',
        subCategory: 'Ø³ÙØ§Ø±Ø§Øª ÙÙØ¨ÙØ¹',
        sellerId: 'seller3',
        sellerName: 'ÙØ¹Ø±Ø¶ Ø§ÙØ³ÙØ§Ø±Ø§Øª',
        sellerRating: 4.6,
        inStock: true,
        rating: 4.6,
        reviewCount: 34,
        createdAt: DateTime.now(),
      ),
      ProductModel(
        id: '5',
        title: 'Ø´ÙØ© ÙÙ Ø­Ø¯Ø©',
        description: 'Ø´ÙØ© 3 ØºØ±Ù ÙÙÙØ 2 Ø­ÙØ§Ù',
        price: 35000000,
        currency: 'YER',
        images: ['https://picsum.photos/id/12/300/300'],
        category: 'Ø¹ÙØ§Ø±Ø§Øª',
        subCategory: 'Ø´ÙÙ ÙÙØ¨ÙØ¹',
        sellerId: 'seller4',
        sellerName: 'Ø§ÙØ¹ÙØ§Ø±Ø§Øª Ø§ÙØ°ÙØ¨ÙØ©',
        sellerRating: 4.5,
        inStock: true,
        rating: 4.5,
        reviewCount: 12,
        createdAt: DateTime.now(),
      ),
    ];
  }
}